version: '3.4'
services:
  mysql:
    image: rbz/mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 60s
      retries: 5
  # WSO2 API Manager as Analytics
  wso2al: 
    image: rbz/wso2al
    ports:
      - "4041:4041"
      - "9444:9443"
      - "9764:9763"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 200s
      timeout: 40s
      retries: 10
      start_period: 30s
    depends_on:
      - mysql
    links:
      - mysql
  # WSO2 Identity Server as Key Manager
  wso2is:
    image: rbz/wso2is
    ports:
      - "9445:9443"
      - "9765:9763"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 200s
      timeout: 40s
      retries: 10
      start_period: 60s
    depends_on:
      - mysql
      - wso2al
    links:
      - mysql
      - wso2al
  # WSO2 API Manager
  wso2am:
    image: rbz/wso2am
    ports:
      - "8243:8243"
      - "8280:8280"
      - "9443:9443"
      - "9763:9763"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 200s
      timeout: 40s
      retries: 10
      start_period: 90s
    depends_on:
      - mysql
      - wso2al
      - wso2is
    links:
      - mysql
      - wso2al
      - wso2is

  httpie:
    image: rbz/httpie
    restart: always
    command: tail -F anything
    container_name: httpie
