version: '2.3'
services:
  mysql:
    image: mysql:5.7.19
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 60s
      retries: 5
  # WSO2 API Manager as Analytics
  wso2al: 
    build: ./wso2al/. 
    ports:
      - "4041:4041"
      - "9444:9443"
      - "9764:9763"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 30s
      timeout: 180s
      retries: 25
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
  # WSO2 Identity Server as Key Manager
  wso2is:
    build: ./wso2is/.
    ports:
      - "9445:9443"
      - "9765:9763"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 30s
      timeout: 180s
      retries: 25
    depends_on:
      mysql:
        condition: service_healthy
      wso2al:
        condition: service_healthy  
    links:
      - mysql
      - wso2al
  # WSO2 API Manager
  wso2am:
    build: ./wso2am/.
    ports:
      - "8243:8243"
      - "8280:8280"
      - "9443:9443"
      - "9763:9763"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 30s
      timeout: 180s
      retries: 25
    depends_on:
      mysql:
        condition: service_healthy
      wso2al:
        condition: service_healthy
      wso2is:
        condition: service_healthy
    links:
      - mysql
      - wso2al
      - wso2is

  httpie:
    build: httpie/.
    restart: always
    command: tail -F anything
    container_name: httpie
